---
title: "StrokeTerritory_Figures"
author: "KLI"
date: "4/9/2019"
output: html_document
---


```{r}
library(broom)
library(ggplot2)
library(plyr)
library(ggpubr)
require(gridExtra)

```

```{r}
data<-read.csv("./181_MetaData+DC.csv")
attach(data)
data$strokeType<-as.factor(data$strokeType)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

my_comparisons <- list( c("1", "2"), c("1", "3"), c("1", "4"), c("2","3"),c("2","4"),c("3","4") )

symnum.args <- list(
  cutpoints = c(0.0000167, 0.000167, 0.00167, 0.008, 1), 
  symbols = c( "***", "**", "*", "ns")
)

```

```{r}
p1=ggplot(data,aes(x=ALI_DC,group=strokeType,fill=strokeType))+
  geom_histogram(position="dodge",bins=5)+
  theme_classic() + 
  ylab("frequency")+
  scale_x_continuous(name="Dice Coefficient", 
                     breaks=c(0,0.2,0.4,0.6,0.8,1.0))+
  scale_fill_manual(name="Stroke Type",
                    breaks=c("1", "2", "3","4"),
                    labels=c("Cortical","Subcortical","Brainstem","Cerebellar"),
                    values=cbPalette)

p1=p1+theme(
  # Hide panel borders and remove grid lines
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black"))+
  ggtitle("ALI")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
#######################

p2=ggplot(data,aes(x=lesion_gnb_DC,group=strokeType,fill=strokeType))+
  geom_histogram(position="dodge",bins=5)+
  theme_classic() + 
  ylab("frequency")+
  scale_x_continuous(name="Dice Coefficient", 
                     breaks=c(0,0.2,0.4,0.6,0.8,1.0))+
  scale_fill_manual(name="Stroke Type",
                    breaks=c("1", "2", "3","4"),
                    labels=c("Cortical","Subcortical","Brainstem","Cerebellar"),
                    values=cbPalette)


p2=p2+theme(
  # Hide panel borders and remove grid lines
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black"))+
  ggtitle("LesionGnb")+
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}

######################

p3=ggplot(data,aes(x=linda_DC,group=strokeType,fill=strokeType))+
  geom_histogram(position="dodge",bins=5)+
  theme_classic() + 
  ylab("frequency")+
  scale_x_continuous(name="Dice Coefficient", 
                     breaks=c(0,0.2,0.4,0.6,0.8,1.0))+
  scale_fill_manual(name="Stroke Type",
                    breaks=c("1", "2", "3","4"),
                    labels=c("Cortical","Subcortical","Brainstem","Cerebellar"),
                    values=cbPalette)


p3=p3+theme(
  # Hide panel borders and remove grid lines
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")
)+
  ggtitle("LINDA")+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}

###################

ggarrange(p1,p2,p3,ncol=3,common.legend=TRUE,legend="bottom")
#ggsave("./strokeTerritory_hist.tiff",dpi=300,width = 7,height=3)


```

```{r}
##################
my_comparisons <- list( c("1", "2"), c("1", "3"), c("1", "4"), c("2","3"),c("2","4"),c("3","4") )

symnum.args <- list(
  cutpoints = c(0.0000167, 0.000167, 0.00167, 0.008, 1), 
  symbols = c( "***", "**", "*", "ns")
)

s1<-ggplot(data, aes(x=strokeType, y=ALI_DC, color=strokeType)) +
  geom_boxplot()+
  theme_classic() +
  labs(title="ALI",x="Stroke Territory", y = "DC")+
  theme(plot.title = element_text(hjust = 0.5))

(s1+scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9","#009E73"),
                     breaks=c("1", "2", "3","4"),
                     labels=c("Cortical","Subcortical","Brainstem","Cerebellar"))+ 
  stat_compare_means(method="wilcox.test",comparisons = my_comparisons,symnum.args = symnum.args) -> s1)


s2<-ggplot(data, aes(x=strokeType, y=lesion_gnb_DC, color=strokeType)) +
  geom_boxplot()+
  theme_classic() +
  labs(title="LesionGnb",x="Stroke Territory", y = "DC")+
  theme(plot.title = element_text(hjust = 0.5))

(s2+scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9","#009E73"),
                       breaks=c("1", "2", "3","4"),
                       labels=c("Cortical","Subcortical","Brainstem","Cerebellar"))+ 
    stat_compare_means(method="wilcox.test",comparisons = my_comparisons,symnum.args = symnum.args) -> s2)

s3<-ggplot(data, aes(x=strokeType, y=linda_DC, color=strokeType)) +
  geom_boxplot()+
  theme_classic() +
  labs(title="LINDA",x="Stroke Territory", y = "DC")+
  theme(plot.title = element_text(hjust = 0.5))

(s3+scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9","#009E73"),
                       breaks=c("1", "2", "3","4"),
                       labels=c("Cortical","Subcortical","Brainstem","Cerebellar"))+ 
    stat_compare_means(method="wilcox.test",comparisons = my_comparisons,symnum.args = symnum.args) -> s3)


ggarrange(s1,s2,s3,ncol=3,nrow=1,common.legend=TRUE,legend = "bottom")
#ggsave("./strokeTerritory_ANOVA.tiff",dpi=300,width = 9,height=5)

```

